package com.bs.dao.mapping;

import com.bs.dao.entity.VisitLog;
import com.bs.dao.entity.VisitLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    int countByExample(VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    int deleteByExample(VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    int insert(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    int insertSelective(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    List<VisitLog> selectByExample(VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    VisitLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VisitLog record, @Param("example") VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VisitLog record, @Param("example") VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VisitLog record);
}