package com.bs.dao.entity;

import java.io.Serializable;

public class Dormitory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.heathlevel
     *
     * @mbggenerated
     */
    private String heathlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.electricityfees
     *
     * @mbggenerated
     */
    private String electricityfees;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.waterfees
     *
     * @mbggenerated
     */
    private String waterfees;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.doorplate
     *
     * @mbggenerated
     */
    private String doorplate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.leadercode
     *
     * @mbggenerated
     */
    private String leadercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.leadername
     *
     * @mbggenerated
     */
    private String leadername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dormitory
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.id
     *
     * @return the value of dormitory.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.id
     *
     * @param id the value for dormitory.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.heathlevel
     *
     * @return the value of dormitory.heathlevel
     *
     * @mbggenerated
     */
    public String getHeathlevel() {
        return heathlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.heathlevel
     *
     * @param heathlevel the value for dormitory.heathlevel
     *
     * @mbggenerated
     */
    public void setHeathlevel(String heathlevel) {
        this.heathlevel = heathlevel == null ? null : heathlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.electricityfees
     *
     * @return the value of dormitory.electricityfees
     *
     * @mbggenerated
     */
    public String getElectricityfees() {
        return electricityfees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.electricityfees
     *
     * @param electricityfees the value for dormitory.electricityfees
     *
     * @mbggenerated
     */
    public void setElectricityfees(String electricityfees) {
        this.electricityfees = electricityfees == null ? null : electricityfees.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.waterfees
     *
     * @return the value of dormitory.waterfees
     *
     * @mbggenerated
     */
    public String getWaterfees() {
        return waterfees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.waterfees
     *
     * @param waterfees the value for dormitory.waterfees
     *
     * @mbggenerated
     */
    public void setWaterfees(String waterfees) {
        this.waterfees = waterfees == null ? null : waterfees.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.doorplate
     *
     * @return the value of dormitory.doorplate
     *
     * @mbggenerated
     */
    public String getDoorplate() {
        return doorplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.doorplate
     *
     * @param doorplate the value for dormitory.doorplate
     *
     * @mbggenerated
     */
    public void setDoorplate(String doorplate) {
        this.doorplate = doorplate == null ? null : doorplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.leadercode
     *
     * @return the value of dormitory.leadercode
     *
     * @mbggenerated
     */
    public String getLeadercode() {
        return leadercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.leadercode
     *
     * @param leadercode the value for dormitory.leadercode
     *
     * @mbggenerated
     */
    public void setLeadercode(String leadercode) {
        this.leadercode = leadercode == null ? null : leadercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.leadername
     *
     * @return the value of dormitory.leadername
     *
     * @mbggenerated
     */
    public String getLeadername() {
        return leadername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.leadername
     *
     * @param leadername the value for dormitory.leadername
     *
     * @mbggenerated
     */
    public void setLeadername(String leadername) {
        this.leadername = leadername == null ? null : leadername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Dormitory other = (Dormitory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getHeathlevel() == null ? other.getHeathlevel() == null : this.getHeathlevel().equals(other.getHeathlevel()))
            && (this.getElectricityfees() == null ? other.getElectricityfees() == null : this.getElectricityfees().equals(other.getElectricityfees()))
            && (this.getWaterfees() == null ? other.getWaterfees() == null : this.getWaterfees().equals(other.getWaterfees()))
            && (this.getDoorplate() == null ? other.getDoorplate() == null : this.getDoorplate().equals(other.getDoorplate()))
            && (this.getLeadercode() == null ? other.getLeadercode() == null : this.getLeadercode().equals(other.getLeadercode()))
            && (this.getLeadername() == null ? other.getLeadername() == null : this.getLeadername().equals(other.getLeadername()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getHeathlevel() == null) ? 0 : getHeathlevel().hashCode());
        result = prime * result + ((getElectricityfees() == null) ? 0 : getElectricityfees().hashCode());
        result = prime * result + ((getWaterfees() == null) ? 0 : getWaterfees().hashCode());
        result = prime * result + ((getDoorplate() == null) ? 0 : getDoorplate().hashCode());
        result = prime * result + ((getLeadercode() == null) ? 0 : getLeadercode().hashCode());
        result = prime * result + ((getLeadername() == null) ? 0 : getLeadername().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", heathlevel=").append(heathlevel);
        sb.append(", electricityfees=").append(electricityfees);
        sb.append(", waterfees=").append(waterfees);
        sb.append(", doorplate=").append(doorplate);
        sb.append(", leadercode=").append(leadercode);
        sb.append(", leadername=").append(leadername);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}