package com.bs.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Res implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res.resname
     *
     * @mbggenerated
     */
    private String resname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res.resnum
     *
     * @mbggenerated
     */
    private String resnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res.updatedate
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res.resstate
     *
     * @mbggenerated
     */
    private String resstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table res
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res.id
     *
     * @return the value of res.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res.id
     *
     * @param id the value for res.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res.resname
     *
     * @return the value of res.resname
     *
     * @mbggenerated
     */
    public String getResname() {
        return resname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res.resname
     *
     * @param resname the value for res.resname
     *
     * @mbggenerated
     */
    public void setResname(String resname) {
        this.resname = resname == null ? null : resname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res.resnum
     *
     * @return the value of res.resnum
     *
     * @mbggenerated
     */
    public String getResnum() {
        return resnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res.resnum
     *
     * @param resnum the value for res.resnum
     *
     * @mbggenerated
     */
    public void setResnum(String resnum) {
        this.resnum = resnum == null ? null : resnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res.updatedate
     *
     * @return the value of res.updatedate
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res.updatedate
     *
     * @param updatedate the value for res.updatedate
     *
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res.resstate
     *
     * @return the value of res.resstate
     *
     * @mbggenerated
     */
    public String getResstate() {
        return resstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res.resstate
     *
     * @param resstate the value for res.resstate
     *
     * @mbggenerated
     */
    public void setResstate(String resstate) {
        this.resstate = resstate == null ? null : resstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Res other = (Res) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getResname() == null ? other.getResname() == null : this.getResname().equals(other.getResname()))
            && (this.getResnum() == null ? other.getResnum() == null : this.getResnum().equals(other.getResnum()))
            && (this.getUpdatedate() == null ? other.getUpdatedate() == null : this.getUpdatedate().equals(other.getUpdatedate()))
            && (this.getResstate() == null ? other.getResstate() == null : this.getResstate().equals(other.getResstate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getResname() == null) ? 0 : getResname().hashCode());
        result = prime * result + ((getResnum() == null) ? 0 : getResnum().hashCode());
        result = prime * result + ((getUpdatedate() == null) ? 0 : getUpdatedate().hashCode());
        result = prime * result + ((getResstate() == null) ? 0 : getResstate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", resname=").append(resname);
        sb.append(", resnum=").append(resnum);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", resstate=").append(resstate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}