package com.bs.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class VisitLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitlog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitlog.visitorname
     *
     * @mbggenerated
     */
    private String visitorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitlog.visitortelephone
     *
     * @mbggenerated
     */
    private String visitortelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitlog.visitobject
     *
     * @mbggenerated
     */
    private String visitobject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitlog.in_date
     *
     * @mbggenerated
     */
    private Date inDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitlog.out_date
     *
     * @mbggenerated
     */
    private Date outDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitlog.visitstate
     *
     * @mbggenerated
     */
    private String visitstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitlog.id
     *
     * @return the value of visitlog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitlog.id
     *
     * @param id the value for visitlog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitlog.visitorname
     *
     * @return the value of visitlog.visitorname
     *
     * @mbggenerated
     */
    public String getVisitorname() {
        return visitorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitlog.visitorname
     *
     * @param visitorname the value for visitlog.visitorname
     *
     * @mbggenerated
     */
    public void setVisitorname(String visitorname) {
        this.visitorname = visitorname == null ? null : visitorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitlog.visitortelephone
     *
     * @return the value of visitlog.visitortelephone
     *
     * @mbggenerated
     */
    public String getVisitortelephone() {
        return visitortelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitlog.visitortelephone
     *
     * @param visitortelephone the value for visitlog.visitortelephone
     *
     * @mbggenerated
     */
    public void setVisitortelephone(String visitortelephone) {
        this.visitortelephone = visitortelephone == null ? null : visitortelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitlog.visitobject
     *
     * @return the value of visitlog.visitobject
     *
     * @mbggenerated
     */
    public String getVisitobject() {
        return visitobject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitlog.visitobject
     *
     * @param visitobject the value for visitlog.visitobject
     *
     * @mbggenerated
     */
    public void setVisitobject(String visitobject) {
        this.visitobject = visitobject == null ? null : visitobject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitlog.in_date
     *
     * @return the value of visitlog.in_date
     *
     * @mbggenerated
     */
    public Date getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitlog.in_date
     *
     * @param inDate the value for visitlog.in_date
     *
     * @mbggenerated
     */
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitlog.out_date
     *
     * @return the value of visitlog.out_date
     *
     * @mbggenerated
     */
    public Date getOutDate() {
        return outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitlog.out_date
     *
     * @param outDate the value for visitlog.out_date
     *
     * @mbggenerated
     */
    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitlog.visitstate
     *
     * @return the value of visitlog.visitstate
     *
     * @mbggenerated
     */
    public String getVisitstate() {
        return visitstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitlog.visitstate
     *
     * @param visitstate the value for visitlog.visitstate
     *
     * @mbggenerated
     */
    public void setVisitstate(String visitstate) {
        this.visitstate = visitstate == null ? null : visitstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VisitLog other = (VisitLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getVisitorname() == null ? other.getVisitorname() == null : this.getVisitorname().equals(other.getVisitorname()))
            && (this.getVisitortelephone() == null ? other.getVisitortelephone() == null : this.getVisitortelephone().equals(other.getVisitortelephone()))
            && (this.getVisitobject() == null ? other.getVisitobject() == null : this.getVisitobject().equals(other.getVisitobject()))
            && (this.getInDate() == null ? other.getInDate() == null : this.getInDate().equals(other.getInDate()))
            && (this.getOutDate() == null ? other.getOutDate() == null : this.getOutDate().equals(other.getOutDate()))
            && (this.getVisitstate() == null ? other.getVisitstate() == null : this.getVisitstate().equals(other.getVisitstate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getVisitorname() == null) ? 0 : getVisitorname().hashCode());
        result = prime * result + ((getVisitortelephone() == null) ? 0 : getVisitortelephone().hashCode());
        result = prime * result + ((getVisitobject() == null) ? 0 : getVisitobject().hashCode());
        result = prime * result + ((getInDate() == null) ? 0 : getInDate().hashCode());
        result = prime * result + ((getOutDate() == null) ? 0 : getOutDate().hashCode());
        result = prime * result + ((getVisitstate() == null) ? 0 : getVisitstate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitlog
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", visitorname=").append(visitorname);
        sb.append(", visitortelephone=").append(visitortelephone);
        sb.append(", visitobject=").append(visitobject);
        sb.append(", inDate=").append(inDate);
        sb.append(", outDate=").append(outDate);
        sb.append(", visitstate=").append(visitstate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}